### ISSUE TITLE
load options failed, Error 1146: Table 'db_limu.pt_option' doesn't exist

### ISSUE THREAD

**Issue by 1476110462** [puti-projects/puti#2]
我使用的docker环境和docker的mysql，使用的link方式连接：
docker版本：
  Version:          19.03.13-ce
  API version:      1.40 (minimum version 1.12)
mysql版本:    mysql  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)

出现一个err，不能正常启动服务，
这是我的config配置文件：
# server
server:
  runmode: debug                 # 开发模式, debug, release, test
  name: puti              # API Server 的名字
  http_port: 8000                  # HTTP 绑定端口
  https_open: false # 是否开启 HTTPS
  https_port: 8080 # HTTPS 绑定端口
  auto_cert: false # 是否开启自动 https
  tls_cert: configs/server.crt # 如果不开启自动 https，配置的证书
  tls_key: configs/server.key # 如果不开启自动 https，配置的证书
  puti_domain: # puti 主应用绑定的域名；例如：example.com
    - puti.com

# safety
safety:
  jwt_secret: putidemojwtseCrect013keyideO

# logger
log:
  logger_file_info: logs/info.log
  logger_file_error: logs/error.log
  logger_max_size: 1024 # megabytes
  logger_max_backups: 7
  logger_max_age: 31 # days

出现的err错误：
2020-11-10 12:32:40	error	option/option.go:64	getting option failed. Option name: site_description. Error 1146: Table 'db_limu.pt_option' doesn't exist

2020-11-10 12:32:40	error	option/option.go:64	getting option failed. Option name: blog_name. Error 1146: Table 'db_limu.pt_option' doesn't exist

希望师傅请给予帮助，谢谢您

**Comment by goozp** [comment]
看看数据库是不是初始化成功了。以及
db.name 数据库名称，还有其它的数据库配置，现在不会应用到初始化的过程中。目前就是一个.sql文件怼进去。因为现在还没有开发安装配置引导步骤。
你看看是否这个问题，如果想改db name的话，还是要手动进容器改。

这是初始化加载配置时找不到表。

**Comment by 1476110462** [comment]
对的，我也刚刚通过debug方式发现了，数据库没有表的，谢谢师傅，跪谢

**Comment by 1476110462** [comment]
> 看看数据库是不是初始化成功了。以及
> db.name 数据库名称，还有其它的数据库配置，现在不会应用到初始化的过程中。目前就是一个.sql文件怼进去。因为现在还没有开发安装配置引导步骤。
> 你看看是否这个问题，如果想改db name的话，还是要手动进容器改。
> 
> 这是初始化加载配置时找不到表。

师傅，可以给个能访问网页的表和后台默认密码嘛

**Comment by goozp** [comment]
初始化完有一个默认账号。
账号 admin 密码 admin

**Comment by 1476110462** [comment]
谢谢您师傅

**Comment by goozp** [comment]
在readme说明了一下。
功能完善后才考虑初始化安装引导功能。

这个先关了。
